/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KiwiBlueprint {
        "message": string;
    }
}
declare global {
    interface HTMLKiwiBlueprintElement extends Components.KiwiBlueprint, HTMLStencilElement {
    }
    var HTMLKiwiBlueprintElement: {
        prototype: HTMLKiwiBlueprintElement;
        new (): HTMLKiwiBlueprintElement;
    };
    interface HTMLElementTagNameMap {
        "kiwi-blueprint": HTMLKiwiBlueprintElement;
    }
}
declare namespace LocalJSX {
    interface KiwiBlueprint {
        "message"?: string;
    }
    interface IntrinsicElements {
        "kiwi-blueprint": KiwiBlueprint;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kiwi-blueprint": LocalJSX.KiwiBlueprint & JSXBase.HTMLAttributes<HTMLKiwiBlueprintElement>;
        }
    }
}
