/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RouteHistory } from "./components/kiwi-navigation-shell/kiwi-navigation-shell.store";
export namespace Components {
    interface KiwiBreadcrumb {
    }
    interface KiwiBreadcrumbItem {
    }
    interface KiwiNavigationShell {
        "breadcrumb": RouteHistory;
        "layout": 'combined' | 'separated';
        "routes": {
    routeKey: string;
    label: string;
    url: (data?: any) => string;
    handler: (data?: any) => RouteHistory;
  }[];
    }
    interface KiwiShellLink {
        "routeData"?: any;
        "routeKey": string;
    }
}
declare global {
    interface HTMLKiwiBreadcrumbElement extends Components.KiwiBreadcrumb, HTMLStencilElement {
    }
    var HTMLKiwiBreadcrumbElement: {
        prototype: HTMLKiwiBreadcrumbElement;
        new (): HTMLKiwiBreadcrumbElement;
    };
    interface HTMLKiwiBreadcrumbItemElement extends Components.KiwiBreadcrumbItem, HTMLStencilElement {
    }
    var HTMLKiwiBreadcrumbItemElement: {
        prototype: HTMLKiwiBreadcrumbItemElement;
        new (): HTMLKiwiBreadcrumbItemElement;
    };
    interface HTMLKiwiNavigationShellElement extends Components.KiwiNavigationShell, HTMLStencilElement {
    }
    var HTMLKiwiNavigationShellElement: {
        prototype: HTMLKiwiNavigationShellElement;
        new (): HTMLKiwiNavigationShellElement;
    };
    interface HTMLKiwiShellLinkElement extends Components.KiwiShellLink, HTMLStencilElement {
    }
    var HTMLKiwiShellLinkElement: {
        prototype: HTMLKiwiShellLinkElement;
        new (): HTMLKiwiShellLinkElement;
    };
    interface HTMLElementTagNameMap {
        "kiwi-breadcrumb": HTMLKiwiBreadcrumbElement;
        "kiwi-breadcrumb-item": HTMLKiwiBreadcrumbItemElement;
        "kiwi-navigation-shell": HTMLKiwiNavigationShellElement;
        "kiwi-shell-link": HTMLKiwiShellLinkElement;
    }
}
declare namespace LocalJSX {
    interface KiwiBreadcrumb {
    }
    interface KiwiBreadcrumbItem {
    }
    interface KiwiNavigationShell {
        "breadcrumb"?: RouteHistory;
        "layout"?: 'combined' | 'separated';
        "routes": {
    routeKey: string;
    label: string;
    url: (data?: any) => string;
    handler: (data?: any) => RouteHistory;
  }[];
    }
    interface KiwiShellLink {
        "routeData"?: any;
        "routeKey": string;
    }
    interface IntrinsicElements {
        "kiwi-breadcrumb": KiwiBreadcrumb;
        "kiwi-breadcrumb-item": KiwiBreadcrumbItem;
        "kiwi-navigation-shell": KiwiNavigationShell;
        "kiwi-shell-link": KiwiShellLink;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kiwi-breadcrumb": LocalJSX.KiwiBreadcrumb & JSXBase.HTMLAttributes<HTMLKiwiBreadcrumbElement>;
            "kiwi-breadcrumb-item": LocalJSX.KiwiBreadcrumbItem & JSXBase.HTMLAttributes<HTMLKiwiBreadcrumbItemElement>;
            "kiwi-navigation-shell": LocalJSX.KiwiNavigationShell & JSXBase.HTMLAttributes<HTMLKiwiNavigationShellElement>;
            "kiwi-shell-link": LocalJSX.KiwiShellLink & JSXBase.HTMLAttributes<HTMLKiwiShellLinkElement>;
        }
    }
}
