name: continuous-integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install root dependencies
        run: npm clean-install

      - name: Install dependencies for all packages
        run: npm run clean-install:all

      - name: Lint all packages
        run: npm run lint:all

      - name: Test all packages
        run: npm run test:all

      - name: Run e2e tests for all packages
        run: npm run test:e2e:all

      - name: Build all packages
        run: npm run build:all
