name: continuous-delivery

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"

      - name: Set git config
        run: |
          git config --local user.email "github@kiwigrid.com"
          git config --local user.name "Kiwigrid | GitHub"

      - name: Add .npmrc file
        run: echo //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN >> .npmrc
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install root dependencies
        run: npm clean-install

      - name: Install dependencies for all packages
        run: npm run clean-install:all

      - name: Lint all packages
        run: npm run lint:all

      - name: Test all packages
        run: npm run test:all

      - name: Run e2e tests for all packages
        run: npm run test:e2e:all

      - name: Build all packages
        run: npm run build:all

      - name: Publish packages
        run: npm run lerna:publish
