/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TFunction } from "i18next";
import { NavigateToEvent } from "./components/kiwi-link/kiwi-link";
import { Placement } from "@popperjs/core/lib";
import { Modifier } from "@popperjs/core/lib/types";
export namespace Components {
    interface KiwiBreadcrumb {
    }
    interface KiwiBreadcrumbItem {
    }
    interface KiwiCheckboxDropdownMenu {
        /**
          * Type of the toggle button.
         */
        "toggleButtonType": 'default' | 'primary' | 'danger' | 'warning' | 'info';
    }
    interface KiwiCheckboxMenu {
    }
    interface KiwiCheckboxMenuItem {
    }
    interface KiwiDropdown {
        /**
          * Css class to be applied to container.
         */
        "containerClass": string;
        /**
          * Type of the toggle button.
         */
        "toggleButtonType": 'default' | 'primary' | 'danger' | 'warning' | 'info';
    }
    interface KiwiI18next {
        /**
          * The key to translate
         */
        "msgKey": string;
    }
    interface KiwiI18nextProvider {
        /**
          * The language to use for i18n. en as default.
         */
        "lng": string;
        /**
          * Base path used to configure i18next backend.
          * @see {BackendOptions#loadPath}
         */
        "loadBasePath": string;
        /**
          * Namespaces to be loaded by i18next
         */
        "ns": string[];
    }
    interface KiwiLabeledCheckbox {
        /**
          * The value of the checkbox.
         */
        "checked": boolean;
        /**
          * The checkbox label.
         */
        "label"?: string;
        /**
          * The name attr of the checkbox.
         */
        "name": string;
    }
    interface KiwiLink {
        /**
          * The navigation destination. Can be either a url or a `NavigateToEvent`
         */
        "to": string | NavigateToEvent;
    }
    interface KiwiModal {
        /**
          * Set this text to show the cancel button, remember to set "withFooter" to show the cancel button
         */
        "cancelText"?: string;
        /**
          * Set to true if the modal should be closed on Escape press
         */
        "escape"?: boolean;
        /**
          * Sets the text of the ok button, remember to set "withFooter" to show the ok button
         */
        "okText"?: string;
        /**
          * Set this to true to show the modal or alternatively set an id to this element and dispatch a 'showKiwiModal' CustomEvent with the id as event.detail
         */
        "open"?: boolean;
        /**
          * Set this to true if you want to show the footer
         */
        "withFooter"?: boolean;
        /**
          * Set this to true if you want to show the header
         */
        "withHeader"?: boolean;
    }
    interface KiwiPopover {
        /**
          * The maximum width of the popover.
         */
        "maxWidth": string;
        /**
          * The minimum width of the popover.
         */
        "minWidth": string;
        /**
          * Popper.js modifiers options. See https://popper.js.org/popper-documentation.html#modifiers
         */
        "modifiers": Modifier<unknown>[];
        /**
          * Placement of the tooltip.
         */
        "placement": Placement;
        /**
          * Show or hide the popover title.
         */
        "showTitle": boolean;
    }
    interface KiwiRibbon {
        /**
          * The bootstrap background color scheme to use, e.g. primary, default, ...
         */
        "backgroundColor"?: | 'gray'
    | 'default'
    | 'primary'
    | 'secondary'
    | 'success'
    | 'info'
    | 'warning'
    | 'danger';
        /**
          * The text to display in the ribbon
         */
        "text"?: string;
        /**
          * The bootstrap text color scheme to use, e.g. primary, default, ...
         */
        "textColor"?: | 'default'
    | 'primary'
    | 'secondary'
    | 'success'
    | 'danger'
    | 'warning'
    | 'info'
    | 'black'
    | 'paper'
    | 'gray'
    | 'charcoal';
    }
}
declare global {
    interface HTMLKiwiBreadcrumbElement extends Components.KiwiBreadcrumb, HTMLStencilElement {
    }
    var HTMLKiwiBreadcrumbElement: {
        prototype: HTMLKiwiBreadcrumbElement;
        new (): HTMLKiwiBreadcrumbElement;
    };
    interface HTMLKiwiBreadcrumbItemElement extends Components.KiwiBreadcrumbItem, HTMLStencilElement {
    }
    var HTMLKiwiBreadcrumbItemElement: {
        prototype: HTMLKiwiBreadcrumbItemElement;
        new (): HTMLKiwiBreadcrumbItemElement;
    };
    interface HTMLKiwiCheckboxDropdownMenuElement extends Components.KiwiCheckboxDropdownMenu, HTMLStencilElement {
    }
    var HTMLKiwiCheckboxDropdownMenuElement: {
        prototype: HTMLKiwiCheckboxDropdownMenuElement;
        new (): HTMLKiwiCheckboxDropdownMenuElement;
    };
    interface HTMLKiwiCheckboxMenuElement extends Components.KiwiCheckboxMenu, HTMLStencilElement {
    }
    var HTMLKiwiCheckboxMenuElement: {
        prototype: HTMLKiwiCheckboxMenuElement;
        new (): HTMLKiwiCheckboxMenuElement;
    };
    interface HTMLKiwiCheckboxMenuItemElement extends Components.KiwiCheckboxMenuItem, HTMLStencilElement {
    }
    var HTMLKiwiCheckboxMenuItemElement: {
        prototype: HTMLKiwiCheckboxMenuItemElement;
        new (): HTMLKiwiCheckboxMenuItemElement;
    };
    interface HTMLKiwiDropdownElement extends Components.KiwiDropdown, HTMLStencilElement {
    }
    var HTMLKiwiDropdownElement: {
        prototype: HTMLKiwiDropdownElement;
        new (): HTMLKiwiDropdownElement;
    };
    interface HTMLKiwiI18nextElement extends Components.KiwiI18next, HTMLStencilElement {
    }
    var HTMLKiwiI18nextElement: {
        prototype: HTMLKiwiI18nextElement;
        new (): HTMLKiwiI18nextElement;
    };
    interface HTMLKiwiI18nextProviderElement extends Components.KiwiI18nextProvider, HTMLStencilElement {
    }
    var HTMLKiwiI18nextProviderElement: {
        prototype: HTMLKiwiI18nextProviderElement;
        new (): HTMLKiwiI18nextProviderElement;
    };
    interface HTMLKiwiLabeledCheckboxElement extends Components.KiwiLabeledCheckbox, HTMLStencilElement {
    }
    var HTMLKiwiLabeledCheckboxElement: {
        prototype: HTMLKiwiLabeledCheckboxElement;
        new (): HTMLKiwiLabeledCheckboxElement;
    };
    interface HTMLKiwiLinkElement extends Components.KiwiLink, HTMLStencilElement {
    }
    var HTMLKiwiLinkElement: {
        prototype: HTMLKiwiLinkElement;
        new (): HTMLKiwiLinkElement;
    };
    interface HTMLKiwiModalElement extends Components.KiwiModal, HTMLStencilElement {
    }
    var HTMLKiwiModalElement: {
        prototype: HTMLKiwiModalElement;
        new (): HTMLKiwiModalElement;
    };
    interface HTMLKiwiPopoverElement extends Components.KiwiPopover, HTMLStencilElement {
    }
    var HTMLKiwiPopoverElement: {
        prototype: HTMLKiwiPopoverElement;
        new (): HTMLKiwiPopoverElement;
    };
    interface HTMLKiwiRibbonElement extends Components.KiwiRibbon, HTMLStencilElement {
    }
    var HTMLKiwiRibbonElement: {
        prototype: HTMLKiwiRibbonElement;
        new (): HTMLKiwiRibbonElement;
    };
    interface HTMLElementTagNameMap {
        "kiwi-breadcrumb": HTMLKiwiBreadcrumbElement;
        "kiwi-breadcrumb-item": HTMLKiwiBreadcrumbItemElement;
        "kiwi-checkbox-dropdown-menu": HTMLKiwiCheckboxDropdownMenuElement;
        "kiwi-checkbox-menu": HTMLKiwiCheckboxMenuElement;
        "kiwi-checkbox-menu-item": HTMLKiwiCheckboxMenuItemElement;
        "kiwi-dropdown": HTMLKiwiDropdownElement;
        "kiwi-i18next": HTMLKiwiI18nextElement;
        "kiwi-i18next-provider": HTMLKiwiI18nextProviderElement;
        "kiwi-labeled-checkbox": HTMLKiwiLabeledCheckboxElement;
        "kiwi-link": HTMLKiwiLinkElement;
        "kiwi-modal": HTMLKiwiModalElement;
        "kiwi-popover": HTMLKiwiPopoverElement;
        "kiwi-ribbon": HTMLKiwiRibbonElement;
    }
}
declare namespace LocalJSX {
    interface KiwiBreadcrumb {
    }
    interface KiwiBreadcrumbItem {
    }
    interface KiwiCheckboxDropdownMenu {
        /**
          * Event signaling that this dropdown was closed.
         */
        "onCloseDropdown"?: (event: CustomEvent<void>) => void;
        /**
          * Type of the toggle button.
         */
        "toggleButtonType"?: 'default' | 'primary' | 'danger' | 'warning' | 'info';
    }
    interface KiwiCheckboxMenu {
    }
    interface KiwiCheckboxMenuItem {
    }
    interface KiwiDropdown {
        /**
          * Css class to be applied to container.
         */
        "containerClass": string;
        /**
          * Event signaling this dropdown is being closed.
         */
        "onCloseDropdown"?: (event: CustomEvent<void>) => void;
        /**
          * Type of the toggle button.
         */
        "toggleButtonType"?: 'default' | 'primary' | 'danger' | 'warning' | 'info';
    }
    interface KiwiI18next {
        /**
          * The key to translate
         */
        "msgKey": string;
    }
    interface KiwiI18nextProvider {
        /**
          * The language to use for i18n. en as default.
         */
        "lng"?: string;
        /**
          * Base path used to configure i18next backend.
          * @see {BackendOptions#loadPath}
         */
        "loadBasePath": string;
        /**
          * Namespaces to be loaded by i18next
         */
        "ns"?: string[];
        "onTFunctionChanged"?: (event: CustomEvent<TFunction>) => void;
    }
    interface KiwiLabeledCheckbox {
        /**
          * The value of the checkbox.
         */
        "checked"?: boolean;
        /**
          * The checkbox label.
         */
        "label"?: string;
        /**
          * The name attr of the checkbox.
         */
        "name": string;
    }
    interface KiwiLink {
        /**
          * Dummy event documentation - please fix me!
         */
        "onNavigateTo"?: (event: CustomEvent<NavigateToEvent>) => void;
        /**
          * The navigation destination. Can be either a url or a `NavigateToEvent`
         */
        "to": string | NavigateToEvent;
    }
    interface KiwiModal {
        /**
          * Set this text to show the cancel button, remember to set "withFooter" to show the cancel button
         */
        "cancelText"?: string;
        /**
          * Set to true if the modal should be closed on Escape press
         */
        "escape"?: boolean;
        /**
          * Sets the text of the ok button, remember to set "withFooter" to show the ok button
         */
        "okText"?: string;
        "onClosed"?: (event: CustomEvent<any>) => void;
        "onConfirmed"?: (event: CustomEvent<any>) => void;
        /**
          * Set this to true to show the modal or alternatively set an id to this element and dispatch a 'showKiwiModal' CustomEvent with the id as event.detail
         */
        "open"?: boolean;
        /**
          * Set this to true if you want to show the footer
         */
        "withFooter"?: boolean;
        /**
          * Set this to true if you want to show the header
         */
        "withHeader"?: boolean;
    }
    interface KiwiPopover {
        /**
          * The maximum width of the popover.
         */
        "maxWidth"?: string;
        /**
          * The minimum width of the popover.
         */
        "minWidth"?: string;
        /**
          * Popper.js modifiers options. See https://popper.js.org/popper-documentation.html#modifiers
         */
        "modifiers"?: Modifier<unknown>[];
        /**
          * Placement of the tooltip.
         */
        "placement"?: Placement;
        /**
          * Show or hide the popover title.
         */
        "showTitle"?: boolean;
    }
    interface KiwiRibbon {
        /**
          * The bootstrap background color scheme to use, e.g. primary, default, ...
         */
        "backgroundColor"?: | 'gray'
    | 'default'
    | 'primary'
    | 'secondary'
    | 'success'
    | 'info'
    | 'warning'
    | 'danger';
        /**
          * The text to display in the ribbon
         */
        "text"?: string;
        /**
          * The bootstrap text color scheme to use, e.g. primary, default, ...
         */
        "textColor"?: | 'default'
    | 'primary'
    | 'secondary'
    | 'success'
    | 'danger'
    | 'warning'
    | 'info'
    | 'black'
    | 'paper'
    | 'gray'
    | 'charcoal';
    }
    interface IntrinsicElements {
        "kiwi-breadcrumb": KiwiBreadcrumb;
        "kiwi-breadcrumb-item": KiwiBreadcrumbItem;
        "kiwi-checkbox-dropdown-menu": KiwiCheckboxDropdownMenu;
        "kiwi-checkbox-menu": KiwiCheckboxMenu;
        "kiwi-checkbox-menu-item": KiwiCheckboxMenuItem;
        "kiwi-dropdown": KiwiDropdown;
        "kiwi-i18next": KiwiI18next;
        "kiwi-i18next-provider": KiwiI18nextProvider;
        "kiwi-labeled-checkbox": KiwiLabeledCheckbox;
        "kiwi-link": KiwiLink;
        "kiwi-modal": KiwiModal;
        "kiwi-popover": KiwiPopover;
        "kiwi-ribbon": KiwiRibbon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kiwi-breadcrumb": LocalJSX.KiwiBreadcrumb & JSXBase.HTMLAttributes<HTMLKiwiBreadcrumbElement>;
            "kiwi-breadcrumb-item": LocalJSX.KiwiBreadcrumbItem & JSXBase.HTMLAttributes<HTMLKiwiBreadcrumbItemElement>;
            "kiwi-checkbox-dropdown-menu": LocalJSX.KiwiCheckboxDropdownMenu & JSXBase.HTMLAttributes<HTMLKiwiCheckboxDropdownMenuElement>;
            "kiwi-checkbox-menu": LocalJSX.KiwiCheckboxMenu & JSXBase.HTMLAttributes<HTMLKiwiCheckboxMenuElement>;
            "kiwi-checkbox-menu-item": LocalJSX.KiwiCheckboxMenuItem & JSXBase.HTMLAttributes<HTMLKiwiCheckboxMenuItemElement>;
            "kiwi-dropdown": LocalJSX.KiwiDropdown & JSXBase.HTMLAttributes<HTMLKiwiDropdownElement>;
            "kiwi-i18next": LocalJSX.KiwiI18next & JSXBase.HTMLAttributes<HTMLKiwiI18nextElement>;
            "kiwi-i18next-provider": LocalJSX.KiwiI18nextProvider & JSXBase.HTMLAttributes<HTMLKiwiI18nextProviderElement>;
            "kiwi-labeled-checkbox": LocalJSX.KiwiLabeledCheckbox & JSXBase.HTMLAttributes<HTMLKiwiLabeledCheckboxElement>;
            "kiwi-link": LocalJSX.KiwiLink & JSXBase.HTMLAttributes<HTMLKiwiLinkElement>;
            "kiwi-modal": LocalJSX.KiwiModal & JSXBase.HTMLAttributes<HTMLKiwiModalElement>;
            "kiwi-popover": LocalJSX.KiwiPopover & JSXBase.HTMLAttributes<HTMLKiwiPopoverElement>;
            "kiwi-ribbon": LocalJSX.KiwiRibbon & JSXBase.HTMLAttributes<HTMLKiwiRibbonElement>;
        }
    }
}
